- name: Demo on vars usage
  hosts: all
  vars:
    URL: play.google.com

  tasks:
    - name: Printing the variable
      ansible.builtin.debug:
        msg: value of the URL is {{URL}}

    - name: Printing the variables
      ansible.builtin.debug:
        msg: value of the URL's is {{URL}}
      vars:
       URL: task.google.com

    - name: using undelated variable
      ansible.builtin.debug:
      mesg: value of the URLT is {{URLT}}     
